# Generated by Django 4.0.4 on 2022-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristics',
            options={'ordering': ['maker']},
        ),
        migrations.AlterModelOptions(
            name='maker',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['motor']},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='nationality',
            name='fullname',
            field=models.CharField(default=1, max_length=50, verbose_name='Celý název:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Jméno státu:'),
        ),
    ]
