# Generated by Django 4.0.4 on 2022-04-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0003_characteristics_tank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristics',
            options={'ordering': ['tank']},
        ),
        migrations.AddField(
            model_name='movement',
            name='tank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tank.tank', verbose_name='Tank:'),
            preserve_default=False,
        ),
    ]
