# Generated by Django 4.0.4 on 2022-05-29 18:28

import django.core.validators
from django.db import migrations, models
import tank.models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0004_alter_characteristics_options_movement_tank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristics',
            options={'ordering': ['tank'], 'verbose_name_plural': 'Characteristics'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['tank']},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['name'], 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AddField(
            model_name='tank',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=tank.models.tank_path, verbose_name='Fotka:'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='cylinders',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)], verbose_name='Počet válců:'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='maxspeed',
            field=models.IntegerField(help_text='Vepište maximální rychlost vozidla (V kilometrech za hodinu)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(150)], verbose_name='Maximální rychlost'),
        ),
    ]
